EXAMPLE_BIN=direct_render
OBJF = ./Sources/options.o \
./Sources/app.o \
./Sources/program.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL1 clanGUI

include ../../Makefile.conf

# EOF #

