EXAMPLE_BIN=direct_render
OBJF = ./Sources/app.o \
./Sources/options.o \
./Sources/precomp.o \
./Sources/program.o

LIBS=clanApp clanDisplay clanCore clanGL1 clanGUI

include ../../Makefile.conf

# EOF #

